{% set version = "0.9.2" %}

package:
  name: taplo
  version: {{ version }}

source:
  url: https://github.com/tamasfe/taplo/archive/refs/tags/release-taplo-cli-{{ version }}.tar.gz
  sha256: 86884b6a2d505d6280ae1304e2bdc434e3b572d05d833833f7189331124f81ae

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}        # [unix]
    - {{ stdlib('c') }}          # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib('m2w64_c') }}    # [win]
    - cargo-bundle-licenses
  host:
    - clangdev  # [not osx]
    - llvmdev   # [not osx]
    - openssl   # [unix]

test:
  requires:
    - m2-grep  # [win]
  commands:
    - taplo --version
    - taplo --help
    - taplo --version | grep -iE "taplo {{ version.replace(".", "\.") }}"

about:
  home: https://github.com/tamasfe/taplo
  license: MIT
  license_family: MIT
  summary: A TOML toolkit written in Rust
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - bollwyvl
